export default {
    vk:"vk.com",
    ok:"ok.ru",
    wa:"Whatsapp",
    vi:"Viber",
    tg:"Telegram",
    wb:"WeChat",
    go:"Google,youtube,Gmail",
    av:"avito",
    fb:"facebook",
    tw:"Twitter",
    ot:"Any other call forwarding",
    ub:"Uber",
    qw:"Qiwi",
    gt:"Gett",
    sn:"OLX",
    ig:"Instagram",
    ss:"hezzl",
    ym:"youla.ru",
    ym:"youla.ru call fr",
    ma:"Mail.ru",
    mm:"Microsoft",
    uk:"Airbnb",
    me:"Line messenger",
    mb:"Yahoo",
    we:"DrugVokrug",
    bd:"5ka.ru",
    kp:"HQ Trivia",
    dt:"Delivery Club",
    ya:"Yandex",
    ya:"Yandex call forwarding",
    mt:"Steam",
    oi:"Tinder",
    fd:"Mamba",
    zz:"DENT",
    kt:"KakaoTalk",
    pm:"AOL",
    tn:"LinkedIN",
    qq:"Tencent QQ",
    mg:"Magnit",
    pf:"pof.com",
    yl:"Yalla",
    kl:"kolesa.kz",
    po:"premium.one",
    nv:"Naver",
    nf:"Netflix",
    iq:"icq",
    ob:"Onlinerby",
    kb:"kufarby",
    im:"Imo",
    mc:"Michat",
    ds:"Discord",
    vv:"Seosprint",
    ji:"Monobank",
    lf:"TikTok/Douyin",
    hu:"Ukrnet",
    wg:"Skout",
    rz:"EasyPay",
    vf:"Q12 Trivia",
    ny:"Pyro Music",
    rr:"Wolt",
    fe:"CliQQ",
    la:"ssoidnet",
    zh:"Zoho",
    gp:"Ticketmaster",
    am:"Amazon",
    ly:"Olacabs",
    tc:"Rambler",
    dp:"ProtonMail",
    pg:"NRJ Music Awards",
    yf:"Citymobil",
    op:"MIRATORG",
    fx:"PGbonus",
    qr:"MEGA",
    yk:"СпортМастер",
    ls:"Careem",
    bl:"BIGO LIVE",
    mu:"MyMusicTaste",
    fu:"Snapchat",
    bf:"Keybase",
    sg:"OZON",
    uu:"Wildberries",
    ua:"BlaBlaCar",
    ab:"Alibaba",
    iv:"Inboxlv",
    zy:"Nttgame",
    gd:"Surveytime",
    fy:"Mylove",
    ce:"mosru",
    tl:"Truecaller",
    hm:"Globus",
    tx:"Bolt",
    ka:"Shopee",
    pl:"Перекресток",
    ip:"Burger King",
    cm:"Prom",
    hw:"AliPay",
    de:"Karusel",
    jc:"IVI",
    rl:"inDriver",
    df:"Happn",
    ui:"RuTube",
    up:"Magnolia",
    nz:"Foodpanda",
    kf:"Weibo",
    ri:"BillMill",
    cc:"Quipp",
    lr:"Okta",
    za:"JDcom",
    da:"MTS CashBack",
    ug:"Fiqsy",
    sq:"KuCoinPlay",
    zr:"Papara",
    xv:"Wish",
    cx:"Icrypex",
    cw:"PaddyPower",
    li:"Baidu",
    dz:"Dominos Pizza",
    xz:"paycell",
    rd:"Lenta",
    qb:"Payberry",
    hz:"Drom",
    gl:"GlobalTel",
    zk:"Deliveroo",
    ia:"Socios",
    xl:"Wmaraci",
    yi:"Yemeksepeti",
    ew:"Nike",
    ae:"myGLO",
    gb:"YouStar",
    cy:"РСА",
    qm:"RosaKhutor",
    dh:"eBay",
    yb:"Система Город",
    qe:"GG",
    yw: 'Grinder',
    ot:"Any other",
};